# Generated by Django 4.2.7 on 2025-10-13 02:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Create Users table
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('password_hash', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_login_date', models.DateField(blank=True, null=True)),
                ('login_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        
        # Create UserMetrics table
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_recorded', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('activity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'user_metrics',
            },
        ),
        
        # Create Goal table
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('muscle_building', 'Muscle Building'), ('endurance', 'Endurance'), ('strength', 'Strength'), ('general_fitness', 'General Fitness')], max_length=50)),
                ('target_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        
        # Create WorkoutPlan table
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('workout_data', models.JSONField(default=dict, help_text='Complete workout plan with exercises, sets, reps, and enriched data')),
                ('difficulty_level', models.CharField(blank=True, help_text="User's fitness level", max_length=50)),
                ('duration_weeks', models.IntegerField(blank=True, null=True)),
                ('days_per_week', models.IntegerField(blank=True, null=True)),
                ('goal', models.CharField(blank=True, help_text="User's fitness goal", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'workout_plans',
            },
        ),
        
        # Create WorkoutLog table
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(default='', max_length=255)),
                ('exercise_data', models.JSONField(blank=True, default=dict, help_text='Store exercise details and enrichment data as JSON')),
                ('date_performed', models.DateTimeField(auto_now_add=True)),
                ('sets_performed', models.IntegerField(default=1)),
                ('reps_performed', models.IntegerField(default=1)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('perceived_effort', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'workout_log',
            },
        ),
        
        # Create NutritionLog table
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_name', models.CharField(default='', max_length=255)),
                ('food_data', models.JSONField(blank=True, default=dict)),
                ('date_eaten', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('meal_type', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'nutrition_log',
            },
        ),
        
        # Create MealPlan table
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('meal_plan_data', models.JSONField(default=dict, help_text='Complete meal plan with days, meals, recipes, ingredients, and nutritional data')),
                ('daily_calorie_target', models.IntegerField(blank=True, null=True)),
                ('days_count', models.IntegerField(blank=True, null=True)),
                ('dietary_preferences', models.JSONField(default=list, help_text='List of dietary preferences')),
                ('goal', models.CharField(blank=True, help_text="User's fitness/nutrition goal", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'meal_plans',
            },
        ),
    ]
