# Generated by Django 4.2.7 on 2025-10-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_schema_restructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='daily_calorie_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='days_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='dietary_preferences',
            field=models.JSONField(default=list, help_text='List of dietary preferences'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='goal',
            field=models.CharField(blank=True, help_text="User's fitness/nutrition goal", max_length=100),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_plan_data',
            field=models.JSONField(default=dict, help_text='Complete meal plan with days, meals, recipes, ingredients, and nutritional data'),
        ),
    ]
