# Generated by Django 4.2.7 on 2025-10-16 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_baseline_schema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="goal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goal",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="goal",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("paused", "Paused"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="goal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="dietary_preferences",
            field=models.JSONField(
                default=list, help_text="List of dietary preferences"
            ),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="goal",
            field=models.CharField(
                blank=True, help_text="User's fitness/nutrition goal", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="mealplan",
            name="meal_plan_data",
            field=models.JSONField(
                default=dict,
                help_text="Complete meal plan with days, meals, recipes, ingredients, and nutritional data",
            ),
        ),
    ]
