# Generated by Django 4.2.7 on 2025-10-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_goal_options_goal_created_at_goal_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionlog",
            name="food_data",
        ),
        migrations.RemoveField(
            model_name="workoutlog",
            name="exercise_data",
        ),
        migrations.AddField(
            model_name="nutritionlog",
            name="calories",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="nutritionlog",
            name="carbs",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="nutritionlog",
            name="protein",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
