# Generated by Django 4.2.7 on 2025-10-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_nutritionlog_food_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionlog",
            name="sugar",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
