# Generated by Django 4.2.7 on 2025-11-16 00:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_nutritionlog_sugar"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutPlanCompletionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("incomplete", "Marked Incomplete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the completion",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completion_logs",
                        to="api.workoutplan",
                    ),
                ),
            ],
            options={
                "db_table": "workout_plan_completion_logs",
                "ordering": ["-logged_at"],
            },
        ),
    ]
