# Generated by Django 4.2.7 on 2025-11-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_add_completion_log_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
