# Generated by Django 4.2.7 on 2025-11-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_workoutplan_completed_at_workoutplan_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutplan",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether this is the user's currently active workout plan",
            ),
        ),
    ]
