# Generated by Django 4.2.7 on 2025-10-13 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_baseline_schema'),
    ]

    operations = [
        # Drop the old MealPlanDay and MealPlanEntry tables if they exist
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS meal_plan_days CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS meal_plan_entries CASCADE;",
            reverse_sql="",
        ),
        
        # Add new JSON fields to meal_plans table if they don't exist
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'meal_plans' AND column_name = 'meal_plan_data'
                ) THEN
                    ALTER TABLE meal_plans ADD COLUMN meal_plan_data JSONB DEFAULT '{}';
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'meal_plans' AND column_name = 'daily_calorie_target'
                ) THEN
                    ALTER TABLE meal_plans ADD COLUMN daily_calorie_target INTEGER;
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'meal_plans' AND column_name = 'days_count'
                ) THEN
                    ALTER TABLE meal_plans ADD COLUMN days_count INTEGER;
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'meal_plans' AND column_name = 'dietary_preferences'
                ) THEN
                    ALTER TABLE meal_plans ADD COLUMN dietary_preferences JSONB DEFAULT '[]';
                END IF;
                
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'meal_plans' AND column_name = 'goal'
                ) THEN
                    ALTER TABLE meal_plans ADD COLUMN goal VARCHAR(100) DEFAULT '';
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE meal_plans DROP COLUMN IF EXISTS meal_plan_data;
            ALTER TABLE meal_plans DROP COLUMN IF EXISTS daily_calorie_target;
            ALTER TABLE meal_plans DROP COLUMN IF EXISTS days_count;
            ALTER TABLE meal_plans DROP COLUMN IF EXISTS dietary_preferences;
            ALTER TABLE meal_plans DROP COLUMN IF EXISTS goal;
            """,
        ),
    ]
