# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_simplify_meal_plan_schema'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS api_recipetag CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS api_recipeingredient CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS api_tag CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS api_ingredient CASCADE;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS api_recipe CASCADE;",
            reverse_sql="",
        ),
    ]