# Generated by Django 4.2.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_recipe_management_tables'),
    ]

    operations = [
        # Add JSONField to workout_plans table
        migrations.RunSQL(
            sql="ALTER TABLE workout_plans ADD COLUMN workout_plan_data JSONB DEFAULT '{}';",
            reverse_sql="ALTER TABLE workout_plans DROP COLUMN workout_plan_data;",
        ),
        
        # Drop plan_exercises table
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS plan_exercises CASCADE;",
            reverse_sql="",
        ),
        
        # Drop plan_days table  
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS plan_days CASCADE;",
            reverse_sql="",
        ),
    ]